import PropTypes from 'prop-types';
import localFont from 'next/font/local';

import './globals.css';

const fsSinclair = localFont({
  src: [
    {
      path: '../public/fonts/FS Sinclair Regular.woff2',
      weight: '400',
    },
    {
      path: '../public/fonts/FS Sinclair Medium.woff2',
      weight: '500',
    },
    {
      path: '../public/fonts/FS Sinclair Bold.woff2',
      weight: '700',
    },
  ],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fsSinclair.className}>{children}</body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};
